apiVersion: v1
kind: Service
metadata:
  name: ngnix-services
  labels:
    role: ngnix-web-pod
  namespace: dev
spec:
  selector:
    version: v1
    role: ngnix-web
  ports:
    - port: 80
      
  type: loadbalancer
